name: test_task_company
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.8
  riverpod_annotation: ^2.3.5
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  uuid: ^4.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

